server:
  port: 9091
  
spring:
  application:
    name: comparison-service
  cloud:
    config:
      discovery:
        enabled: true
    failFast: true
 
ribbon:
  eureka:
    enabled: false
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_URL:localhost}:8061/eureka/
    healthcheck:
      enabled: true
