server:
  port: 9092
 
spring:
  application:
    name: db-service
  cloud:
    config:
      discovery:
        enabled: true
  data:
    mongodb:
      uri: mongodb://${DB_URL:localhost}/articles
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_URL:localhost}:8061/eureka/
    healthcheck:
      enabled: true
      
