server:
  port: 9092
 
spring:
  application:
    name: db-service
  cloud:
    config:
      discovery:
        enabled: true
    failFast: true
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
    healthcheck:
      enabled: true
      
spring:
  data:
    mongodb:
      uri: mongodb://localhost/articles
