server:
  port: 9092
  connection-timeout:20000
 
spring:
  application:
    name: db-service
  cloud:
    config:
      discovery:
        enabled: true
  data:
    mongodb:
      uri: mongodb://${DB_URL:localhost}/articles
    
ribbon:
  eureka:
    enabled: false

eureka:
  hostname: db-service
  port: 9092
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_URL:localhost}:8061/eureka/
    healthcheck:
      enabled: true
      
