server:
  port: 8061
  
spring:
  application:
    name: discovery-service
  cloud:
    config:
      discovery:
        enabled: true
 
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${EUREKA_URL:localhost}:${server.port}/eureka/
  server:
    peer-node-read-timeout-ms: 60000