server:
  port: 8061
  
spring:
  application:
    name: discovery-service
  cloud:
    config:
      discovery:
        enabled: true
      failFast: true
 
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/