server:
  port: 8060
  
spring:
  application:
    name: gateway-service
  cloud:
    config:
      discovery:
        enabled: true
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_URL:localhost}:8061/eureka/
    healthcheck:
      enabled: true
    fetchRegistry: true
        
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
zuul:
  routes:
    core:
      path: /core/**
      serviceId: main-service
    simpleclient:
      path: /simpleclient/**
      serviceId: simpleclient-service
    db:
      path: /db/**
      serviceId: db-service