server:
  port: 8060
  
spring:
  application:
    name: gateway-service
  cloud:
    config:
      discovery:
        enabled: true
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false
      gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: main-service
        uri: lb://${MAIN_URL:localhost}:9090
        predicates:
        - Path=/core/**
      - id: db-service
        uri: lb://${DB_URL:localhost}:9092
        predicates:
        - Path=/db/**
      - id: simpleclient-service
        uri: lb://${SIMPLE_URL:localhost}:9091
        predicates:
        - Path=/simpleclient/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_URL:localhost}:8061/eureka/
    healthcheck:
      enabled: true
    fetchRegistry: true
        
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
     

hystrix:
   command:
      default:
         execution:
            iso lation:
               thread:
                  timeoutInMilliseconds: 30000


ribbon:
   ReadTimeout: 60000
   connection-timeout: 3000
   eureka:
      enabled: true
  