server:
  port: 8060
  
spring:
  application:
    name: gateway-service
  cloud:
    config:
      discovery:
        enabled: true
    failFast: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
    healthcheck:
      enabled: true

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
zuul:
  routes:
    core:
      path: /core/**
      serviceId: main-service
    simpleclient:
      path: /simpleclient/**
      serviceId: simpleclient-service
    db:
      path: /db/**
      serviceId: db-service
  ws:
  brokerages:
    compare:
      end-points: /ws
      brokers:  /topic
      destination-prefixes: /app
     
