server:
  port: 8060
  connection-timeout:20000
  
spring:
  application:
    name: gateway-service
  cloud:
    config:
      discovery:
        enabled: true
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_URL:localhost}:8061/eureka/
    healthcheck:
      enabled: true
    fetchRegistry: true
        
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
     

hystrix:
   command:
      default:
         execution:
            iso lation:
               thread:
                  timeoutInMilliseconds: 30000


ribbon:
   ReadTimeout: 60000
   connection-timeout: 3000
   eureka:
      enabled: true
      
zuul:
  ignoredServices: '*'
  host:
      time-to-live: -1
      connect-timeout-millis: 5000
      max-per-route-connections: 10000
      max-total-connections: 5000
      socket-timeout-millis: 60000
  semaphore:
      max-semaphores: 500    
  routes:
    core:
      path: /core/**
      serviceId: main-service
    simpleclient:
      path: /simpleclient/**
      serviceId: simpleclient-service
    db:
      path: /db/**
      serviceId: db-service