server:
  port: 9090
  
spring:
  application:
    name: main-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
            - "*"
            allowedMethods: 
            - "*"
            allowed-headers:
            - "*"
    config:
      discovery:
        enabled: true
    failFast: true
  sleuth:
    integration:
      websockets:
        enabled: false
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_URL:localhost}:8061/eureka/
    healthcheck:
      enabled: true
      