server:
  port: 9090
  connection-timeout:20000
  
spring:
  application:
    name: main-service
  cloud:
    config:
      discovery:
        enabled: true
    failFast: true
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_URL:localhost}:8061/eureka/
    healthcheck:
      enabled: true
      