server:
  port: 9091
  
spring:
  application:
    name: simpleclient-service
  cloud:
    config:
      discovery:
        enabled: true
    failFast: true
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_URL:localhost}:8061/eureka/
    healthcheck:
      enabled: true
